import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/nextjs_olderversion/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Sky Web",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="max-w-3xl mx-auto p-4">
          <NavBar />
        <div className="mt-8">
          {children}
        </div>
        </div>
      </body>
    </html>
  );
}
